### ISSUE TITLE
GCP example missing.

### ISSUE THREAD

**Issue by mcartagenah** [spotty-cloud/spotty#102]
Hi, I couldn't find a gcp example besides the one in #68 , but I get the following error:

```
Preparing the deployment template...
  Error:
  ------
  <HttpError 404 when requesting https://compute.googleapis.com/compute/v1/projects/ml-images/global/images/family/common-gce-gpu-image?alt=json returned "The resource 'projects/ml-images/global/images/family/common-gce-gpu-image' was not found". Details: "[{'message': "The resource 'projects/ml-images/global/images/family/common-gce-gpu-image' was not found", 'domain': 'global', 'reason': 'notFound'}]">
```

What am I doing wrong?

**Comment by turian** [comment]
@apls777 I have the same issue and it's urgent :(

This is my spotty.yaml, could you show a simple working GCP spotty yaml?

```
project:
  name: spotty-heareval
  syncFilters:
    - exclude:
        - .idea/*
        - .git/*
        - '*/__pycache__/*'
        - _workdir
        - embeddings

containers:
  - projectDir: /workspace/project
    file: Dockerfile
#    ports:
#      # TensorBoard
#      - containerPort: 6006
#        hostPort: 6006
#      # Jupyter
#      - containerPort: 8888
#        hostPort: 8888
    volumeMounts:
      - name: workspace
        mountPath: /workspace
    runtimeParameters: ['--shm-size', '20G']

instances:
  - name: spotty-heareval-i1
    provider: gcp
    parameters:
      zone: europe-west4-a
      # A100 TODO: Try others
      machineType: a2-highgpu-1g
#      spotInstance: True
#      ports: [6006, 8888]
      dockerDataRoot: /docker
      volumes:
        - name: workspace
          parameters:
            size: 250
# Not implemented for GCP, all volumes will be retained
#            deletionPolicy: retain
            mountDir: /workspace
        - name: docker
          parameters:
            size: 20
            mountDir: /docker

scripts:
  setup: |
    bash setup.sh
  train: |
    bash train.sh
#  tensorboard: |
#    tensorboard --bind_all --port 6006 --logdir /workspace/project/logs
#  jupyter: |
#    jupyter notebook --allow-root --ip 0.0.0.0 --notebook-dir=/workspace/project
```
