### ISSUE TITLE
Cannot mount second volume

### ISSUE THREAD

**Issue by turian** [spotty-cloud/spotty#82]
I have an old volume I am trying to attach to a new instance. I renamed the old instance so it should be fine.

Here is my config:

```
  - name: ietl
    provider: aws
    parameters:
      region: eu-central-1
      # These GPU instances are more reliable to create with the GPU docker so ¯\_(ツ)_/¯
      instanceType: p3.2xlarge
#      instanceType: t3.2xlarge
#      instanceType: t4g.2xlarge
      spotInstance: True
      ports: [6006, 8888]
      dockerDataRoot: /docker
      volumes:
        - name: workspace
          parameters:
            size: 1000
            deletionPolicy: retain
            mountDir: /workspace
        - name: oldworkspace
          parameters:
            size: 600
            deletionPolicy: retain
            mountDir: /oldworkspace
        - name: docker
          parameters:
            size: 20
            mountDir: /docker
```

While it's loading, I get this message:

```

Volumes:
+--------------+------------+------------+-----------------+
| Name         | Mount Path | Type       | Deletion Policy |
+==============+============+============+=================+
| workspace    | /workspace | EBS volume | Retain Volume   |
+--------------+------------+------------+-----------------+
| oldworkspace | -          | EBS volume | Retain Volume   |
+--------------+------------+------------+-----------------+
| docker       | -          | EBS volume | Retain Volume   |
+--------------+------------+------------+-----------------+
```

Note there is no mount path. I don't see it in the machine!
