### ISSUE TITLE
Stuck at "- launching the instance..."

### ISSUE THREAD

**Issue by j-o-d-o** [spotty-cloud/spotty#90]
I have no issues creating t2 spot instances e.g. t2.medium. But somehow for p3.2xlarge spotty is stuck at "- launching the instance...".

Here is my config:
```yaml
project:
  name: cvms
  syncFilters:
    - exclude:
      - .git/*
      - .idea/*
      - '*/__pycache__/*'
      - tmp/*
      - dependencies/*

containers:
  - projectDir: /workspace/computer-vision-models
    hostNetwork: true
    file: Dockerfile
    env:
      PYTHONPATH: /workspace/computer-vision-models
    volumeMounts:
      - name: workspace
        mountPath: /workspace

instances:
  - name: train
    provider: aws
    parameters:
      region: eu-west-2
      instanceType: p3.2xlarge
      availabilityZone: eu-west-2a
      spotInstance: true
      dockerDataRoot: /docker
      volumes:
        - name: workspace
          parameters:
            size: 30
            deletionPolicy: retain
        - name: docker
          parameters:
            size: 30
            mountDir: /docker
            deletionPolicy: retain

scripts:
  train: |
    python models/semseg/train.py
  tensorboard: |
    tensorboard --bind_all --port 6006 --logdir /workspace/computer-vision-models/trained_models
```

Any idea what could go wrong here?
