### ISSUE TITLE
How to copy files in dockerfile without root build context

### ISSUE THREAD

**Issue by himat** [spotty-cloud/spotty#93]
I'm trying to use spotty for the first time but I ran into an error after running `spotty start` and it tried to build my docker container:
```
 Step 2/5 : COPY requirements.txt requirements.txt
 COPY failed: file not found in build context or excluded by .dockerignore: stat requirements.txt: file does not exist
```

My directory structure
```
proj/
  docker/
    models.Dockerfile
  src/*
  requirements.txt
  spotty.yaml
```

Here's my dockerfile: `docker/models.Dockerfile`
```
FROM python:3.8.7-buster

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
```

Here's my spotty config: `spotty.yaml`
```
project:
  name: model-server
  syncFilters:
    - exclude:
        - .idea/*
        - .git/*
        - .mypy_cache/*
        - '*/__pycache__/*'
        - '*/*.swp'
containers:
  - projectDir: /workspace/project
    file: docker/models.Dockerfile
    ports:
      # Server
      - containerPort: 5000
        hostPort: 5000
    volumeMounts:
      - name: workspace
        mountPath: /workspace
instances:
  - name: model-server-inst
    provider: aws
    parameters:
      region: us-east-2
      instanceType: t2.small
      dockerDataRoot: /
      volumes:
        - name: workspace
          parameters:
            size: 50
            deletionPolicy: retain
        - name: docker
          parameters:
            size: 10
            mountDir: /docker
            deletionPolicy: retain
```

I saw in the [docs](https://spotty.cloud/docs/user-guide/configuration-file.html) that `Note: Spotty uses the directory with the Dockerfile as its build context`.
So this seems like why I ran into this issue since the requirements.txt file is not present in the docker context.

So is there a way to get around this, or does using spotty mean that I need to keep my dockerfile in my root directory? Or is there something I'm doing wrong.
